Repository stdNullPtr/TorchLight-SpigotMC, pull requests merged in 2025-03, with the labels that each got.

#12 Adding light time in config file
  .idea/git_toolbox_blame.xml
  .idea/inspectionProfiles/Project_Default.xml
  pom.xml
  src/main/java/com/stdnullptr/PluginMain.java
  src/main/java/com/stdnullptr/constants/Commands.java
  src/main/java/com/stdnullptr/constants/Config.java
  src/main/java/com/stdnullptr/constants/Permissions.java
  src/main/java/com/stdnullptr/listener/PlayerMoveEventListener.java
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: enhancement

#15 chore(master): release 1.0.0
  CHANGELOG.md
Labels: autorelease: pending

#23 feat(commands): Implement command pattern
  src/main/java/com/stdnullptr/PluginMain.java
  src/main/java/com/stdnullptr/command/CommandManager.java
  src/main/java/com/stdnullptr/command/TorchLightCommand.java
  src/main/java/com/stdnullptr/command/impl/OffCommand.java
  src/main/java/com/stdnullptr/command/impl/OnCommand.java
  src/main/java/com/stdnullptr/command/impl/TimeCommand.java
Labels: enhancement, refactor

#22 chore(master): release 1.3.0
  .github/.release-please-manifest.json
  .github/CHANGELOG.md
  src/main/resources/plugin.yml
Labels: autorelease: pending

#30 feat: Improve performance
  README.md
  src/main/java/com/stdnullptr/PluginMain.java
  src/main/java/com/stdnullptr/command/CommandManager.java
  src/main/java/com/stdnullptr/command/impl/LightLevelCommand.java
  src/main/java/com/stdnullptr/command/impl/StatusCommand.java
  src/main/java/com/stdnullptr/command/impl/TimeCommand.java
  src/main/java/com/stdnullptr/constants/Commands.java
  src/main/java/com/stdnullptr/constants/Config.java
  src/main/java/com/stdnullptr/constants/Game.java
  src/main/java/com/stdnullptr/listener/PlayerActivityEventListener.java
  src/main/java/com/stdnullptr/listener/PlayerMoveEventListener.java
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: documentation, enhancement

#25 chore(master): release 1.4.0
  .github/.release-please-manifest.json
  .github/CHANGELOG.md
  src/main/resources/plugin.yml
Labels: autorelease: pending
